### ISSUE TITLE
Add microphone block

### ISSUE THREAD

**Issue by gnzlbg** [regolith-linux/regolith-i3xrocks-config#105]
Add a microphone block, that shows up if the microphone is muted or not, and that lets you control the microphone volume.

**Comment by nicolas-lopez** [comment]
Hello I would like to submit this script for microphone handling: https://pastebin.com/xSYVzY93
Unfortunately I don't have time to make a proper pull request

**Comment by kgilmer** [comment]
Thanks @nicolas-lopez !  I've created a PR from your paste.  https://github.com/regolith-linux/regolith-i3xrocks-config/pull/117

**Comment by jc00ke** [comment]
This can be closed, yeah?

**Comment by kgilmer** [comment]
Yep, thanks @jc00ke
