### ISSUE TITLE
show  RAM usage by percentage 

### ISSUE THREAD

**Issue by feima0011** [regolith-linux/regolith-i3xrocks-config#106]
The CPU usage is shown as percentage by default. 
It would be nice to have RAM usage shown by percentage.

**Comment by XaverKlemenschits** [comment]
For anyone looking for a way to set it up so memory usage is shown as percentage of used memory (like CPU):

Add a file at `~/.config/regolith2/i3xrocks/conf.d` with the following content:
```
# Memory
[memory]
interval=10
display=used
type=mem
percentage=true
```
`display` can be one of:
- free
- used

`type` can be one of:
- mem
- swap

Documentation for details: https://regolith-desktop.com/docs/howtos/add-remove-blocklets/

**Comment by kgilmer** [comment]
Marking as addressed, thanks @XaverKlemenschits .  Kindly re-open if this does not resolve the issue.
