### ISSUE TITLE
Weather blocklet 404s

### ISSUE THREAD

**Issue by jc00ke** [regolith-linux/regolith-i3xrocks-config#116]
Google says it's 46F here in Portland right now, but the `weather` blocklet says 23F. So I clicked on the blocklet and I'm presented with ` 404 UNKNOWN LOCATION: Portland45.4383, Oregon, United States`

![image](https://user-images.githubusercontent.com/18191/108006965-a3076f00-6fb1-11eb-9302-e9dd2609029b.png)

```
❯ /usr/share/i3xrocks/weather
<span font_desc="Source Code Pro Medium 13" color="#93a1a1">🌨  +23°F</span>
~                                                                                                                                             ~
❯ weather_location=Portland /usr/share/i3xrocks/weather
<span font_desc="Source Code Pro Medium 13" color="#93a1a1">⛅️  +46°F</span>
~
❯ xrescat i3xrocks.weather.location
~
❯
```

```
Package: i3xrocks-weather
Version: 3.5.7-1
Priority: optional
Section: x11
Source: regolith-i3xrocks-config
Maintainer: Ken Gilmer <kgilmer@gmail.com>
Installed-Size: 24.6 kB
Depends: regolith-i3xrocks-config, curl, fonts-noto-color-emoji, xdg-utils
Download-Size: 9,052 B
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/regolith-linux/release/ubuntu groovy/main amd64 Packages
Description: Indicator to show local weather.
 An i3xrocks indicator for showing the local weather.
```

Is there any other info I can provide? Thanks!

**Comment by moritzheiber** [comment]
Hey, thanks for point this out. It's a bug in `wttr.in`, the service we use for displaying accurate weather data. For now, the only workaround is to set `weather_location` until it is fixed.

Tracking bug github.com/chubin/wttr.in/#576

**Comment by kgilmer** [comment]
Upstream bug closed, closing this one.  Please re-open if issue persists.
