### ISSUE TITLE
Click action for Weather doesn't include format and unit options

### ISSUE THREAD

**Issue by majorhayes** [regolith-linux/regolith-i3xrocks-config#120]
https://github.com/regolith-linux/regolith-i3xrocks-config/blob/ebf1299fbac21a206df854fcdb35c52dc47fb4d3/scripts/weather#L23

vs

https://github.com/regolith-linux/regolith-i3xrocks-config/blob/ebf1299fbac21a206df854fcdb35c52dc47fb4d3/scripts/weather#L32

**Comment by kgilmer** [comment]
Well if we pass format, by default that is "1" and wttr just prints temp very minimally at the top of the page and nothing else.  Is it units that you're after specifically or something else @majorhayes ?

**Comment by majorhayes** [comment]
Units.

At work I use a VPN based in UK but I'm in the US so the weather defaults to C unless I put "u" in the format, which works for the i3xrocks display but not for the link to open the forecast in the browser.

**Comment by kgilmer** [comment]
This will be available for testing in the `unstable` PPA as `regolith-i3xrocks-config` version `3.6.5-1`.
