### ISSUE TITLE
Microphone block using volume config

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-i3xrocks-config#121]
```bash
.../i3xrocks/conf.d$ cat 80_microphone 
# volume
#
# Display Volume
[volume]
interval=5
```

**Comment by jc00ke** [comment]
Happy to help test. Even with that commented out I would expect the defaults to kick in, yeah?

**Comment by kgilmer** [comment]
Whoops, I forgot to associate the commit to this issue.  See here for the necessary changes: https://github.com/regolith-linux/regolith-i3xrocks-config/commit/d0400b8ed604d30230e8b1854ae80a609997245d

I've got it running locally and seems to be working as expected, although I don't use this computer as much for tasks that require the mic.

**Comment by jc00ke** [comment]
I applied that change and it's all good. Thanks!

**Comment by kgilmer** [comment]
This has been resolved in Regolith 2
