### ISSUE TITLE
Update i3xrocks-openvpn

### ISSUE THREAD

**Issue by hab25** [regolith-linux/regolith-i3xrocks-config#122]
I believe `i3xrocks-openvpn` (code is here https://github.com/regolith-linux/regolith-i3xrocks-config/blob/master/scripts/openvpn) only supports the `openvpn` client, and not `openvpn3`. 

I think nowadays most users will be using  `openvpn3`, as it is the newest client and the default recommendation of the OpenVPN company. See https://openvpn.net/openvpn-client-for-linux/ and https://openvpn.net/cloud-docs/openvpn-3-client-for-linux/ for proof of the last statement.

Therefore, I believe `i3xrocks-openvpn` should be accordingly updated (or deprecated).

**Comment by kgilmer** [comment]
It doesn't appear that `openvpn3` is packaged for Debian or Ubuntu.  We'd need that packaging done before we could have a i3xrocks indicator that uses it.

**Comment by jjnesbitt** [comment]
`openvpn3` is now packaged for debian and ubuntu, can this be re-opened?
