### ISSUE TITLE
i3xrocks-temp - invalid output

### ISSUE THREAD

**Issue by klew** [regolith-linux/regolith-i3xrocks-config#123]
Hi

Current parser of `sensors` output doesn't work in my case (there is no single entry with "Core" or "Tdie").
I use Ubuntu 21.10 with Regolith 1.6. 
sensors version 3.6.0 with libsensors version 3.6.0

Here is my output from `sensors` command:
```
amdgpu-pci-0500
Adapter: PCI adapter
vddgfx:        1.44 V  
vddnb:         1.34 V  
edge:         +40.0°C  
power1:        4.00 mW 

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +16.8°C  (crit = +20.8°C)

gigabyte_wmi-virtual-0
Adapter: Virtual device
temp1:        +36.0°C  
temp2:        +46.0°C  
temp3:        +43.0°C  
temp4:        +24.0°C  
temp5:        +43.0°C  
temp6:        +49.0°C  

nvme-pci-0400
Adapter: PCI adapter
Composite:    +37.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +37.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +45.9°C  (low  = -273.1°C, high = +65261.8°C)

```

temp3 is a CPU temperature.

**Comment by cfsmp3** [comment]
> Here is my output from sensors command:

The output of sensors -u would be more useful. It will give you each value in the easy to parse way the script uses.

Once you've found the right variable, add it to ~/.config/regolith/Xresources with the key "i3xrocks.temp.key"

Remember to restart i3 (for example, with regolith-look refresh) after modifying Xresources.

**Comment by klew** [comment]
Latest version of temp script is not using -u nor i3xrocks.temp.key.
I actually reverted my local copy of that script to older version which was using those, but with this issue I'm not looking for help, but rather I report problem with current version.

**Comment by jc00ke** [comment]
I'm seeing this issue now too. I never had `i3xrocks.temp.key` set but I could see that being valuable since my key is `Tctl`.

```
> sensors
nvme-pci-0100
Adapter: PCI adapter
Composite:    +38.9°C  (low  = -273.1°C, high = +80.8°C)
                       (crit = +80.8°C)
Sensor 1:     +38.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +64.8°C  (low  = -273.1°C, high = +65261.8°C)

k10temp-pci-00c3          <--------------
Adapter: PCI adapter
Tctl:         +36.8°C     <--------------
Tccd1:        +38.8°C  
Tccd2:        +36.8°C  

amdgpu-pci-2d00
Adapter: PCI adapter
vddgfx:      918.00 mV 
fan1:        2070 RPM  (min = 1800 RPM, max = 6900 RPM)
edge:         +39.0°C  (crit = +97.0°C, hyst = -273.1°C)
power1:        8.08 W  (cap =  35.00 W)

```

@moritzheiber did you have a reason in 5149355f3dd186ffe1c74d1fa35c4e646e2b5925 to remove the `$TEMP_KEY` part?

If not, seems like we should add that back.

**Comment by peturh** [comment]
I have an issue that `i3xrocks-temp` shows `MIN_INT` value (-2147483647).

I'm running `regolith-deskptop` on Ubuntu and I just created the file `~.config/regolith/Xresources` containing:

```
i3xrocks.temp.key: CPU
```
This is my sensors output:

```
thinkpad-isa-0000
Adapter: ISA adapter
fan1:        3600 RPM
CPU:          +76.0°C  
GPU:           +0.0°C  
temp3:         +0.0°C  
temp4:         +0.0°C  
temp5:         +0.0°C  
temp6:         +0.0°C  
temp7:         +0.0°C  
temp8:            N/A  

nvme-pci-0100
Adapter: PCI adapter
Composite:    +31.9°C  (low  =  -0.1°C, high = +79.8°C)
                       (crit = +82.8°C)

amdgpu-pci-0700
Adapter: PCI adapter
vddgfx:        1.18 V  
vddnb:       631.00 mV 
edge:         +57.0°C  
slowPPT:       3.00 mW 

BAT0-acpi-0
Adapter: ACPI interface
in0:          11.48 V  
```

It still shows negative MIN_INT value. What am I missing?

**Comment by rojopolis** [comment]
> I'm seeing this issue now too. I never had `i3xrocks.temp.key` set but I could see that being valuable since my key is `Tctl`.
> 
> ```
> > sensors
> nvme-pci-0100
> Adapter: PCI adapter
> Composite:    +38.9°C  (low  = -273.1°C, high = +80.8°C)
>                        (crit = +80.8°C)
> Sensor 1:     +38.9°C  (low  = -273.1°C, high = +65261.8°C)
> Sensor 2:     +64.8°C  (low  = -273.1°C, high = +65261.8°C)
> 
> k10temp-pci-00c3          <--------------
> Adapter: PCI adapter
> Tctl:         +36.8°C     <--------------
> Tccd1:        +38.8°C  
> Tccd2:        +36.8°C  
> 
> amdgpu-pci-2d00
> Adapter: PCI adapter
> vddgfx:      918.00 mV 
> fan1:        2070 RPM  (min = 1800 RPM, max = 6900 RPM)
> edge:         +39.0°C  (crit = +97.0°C, hyst = -273.1°C)
> power1:        8.08 W  (cap =  35.00 W)
> ```
> 
> @moritzheiber did you have a reason in [5149355](https://github.com/regolith-linux/regolith-i3xrocks-config/commit/5149355f3dd186ffe1c74d1fa35c4e646e2b5925) to remove the `$TEMP_KEY` part?
> 
> If not, seems like we should add that back.

Reverting this fixed it for me.

**Comment by mfisher87** [comment]
Either reverting 5149355 or applying the change in pull request #124 resolve this issue for me.

**Comment by kgilmer** [comment]
Linked PR was merged, closing.
