### ISSUE TITLE
i3xrocks-volume - volume below 10% not shown

### ISSUE THREAD

**Issue by sdrwtf** [regolith-linux/regolith-i3xrocks-config#135]
Hey,

I'm currently testing regolith with an virtual minimal Ubuntu installation (like it's described here https://regolith-desktop.com/docs/howtos/minimal-ubuntu-install/) and figured out that if I change the volume below 10% the volume is not displayed anymore:

![image](https://user-images.githubusercontent.com/34947398/178007689-87a64e0d-effa-46a0-9fbb-732799a72e2d.png)

If the volume is >= 10% everything is fine:

![image](https://user-images.githubusercontent.com/34947398/178008018-cf173e28-41c5-4b16-a904-5d061a7caa1d.png)

The same behavior applies for the microphone volume.

The reason seems to be the `sed` regex which is used within the `mixer_value` function: https://github.com/regolith-linux/regolith-i3xrocks-config/blob/7bb3464cc56ec3e42830e9126a246769a86d3bba/scripts/volume#L66

I think it would be better to only filter on a single number and add a `0` prefix in case the value is less than 10, for example:

```bash
mixer_value() {
    VAL=$(mixer_info | sed -n -E "s/.*\[(-?[0-9]+)$UNIT\].*/\1/p" | head -n 1)
    if [ -z "$VAL" ]; then
        # return empty string of same width to prevent bar shift.
        echo "   "
    elif [ "$VAL" -lt "10" ]; then
        echo "0$VAL$UNIT"
    else
        echo "$VAL$UNIT"
    fi
}
```
So volume below 10% is also displayed as expected:

![image](https://user-images.githubusercontent.com/34947398/178010162-dffa666a-62e0-4c66-a2b8-064e3cdd67e7.png)

**Comment by kgilmer** [comment]
Hi @sdrwtf !  Thanks for the detailed bug report and fix proposal.  I don't see any problems with your update.  Would you like to setup a Pull Request?
