### ISSUE TITLE
Wrong icons on blocklets

### ISSUE THREAD

**Issue by diogoalmeida** [regolith-linux/regolith-i3xrocks-config#147]
Hi,

I've been struggling to setup i3xrocks such that blocklets render their icons/glyphs correctly. In some cases, like with `cpu-usage`, the icon isn't rendered  while for others the icons are just swapped. See screenshot:
![image](https://user-images.githubusercontent.com/1499341/210600929-94a58e94-5d32-4965-9450-a2f6f03bfed9.png)

This corresponds to the following configuration:
```bash
 ~/.config/regolith2/i3xrocks/conf.d  ls 
01_setup      20_keyboard-layout  50_memory   80_microphone  90_time
02_cpu-usage  50_disk-capacity    80_battery  80_volume
```

Any tips on how I can fix this issue? Thanks in advance!

**Comment by kgilmer** [comment]
Hi @diogoalmeida I'm not sure if you're having issues with the built-in blocklets or you're customizing them.  (also assuming Regolith 2.x)  In either case your bar font must be set to a [nerdfonts](https://www.nerdfonts.com/)  If it's the latter, you need to specify the font glyph character from your configured bar font.  I use  `gucharmap` application to select the font and find the glyph I want for a given block, but web or other ways can also be used to copy and paste the character.

**Comment by diogoalmeida** [comment]
Hi @kgilmer , thanks for the quick reply.

Indeed I am on Regolith 2.2. I installed it on top of my existing Ubuntu 20.04 system, following [these instructions
](https://regolith-desktop.com/#get-regolith-22). 
I am having issues with the built-in blockets. The only customization I have done so far was to specify my own `conf.d` as in the original message.

I am using the "dracula" look. I have the font `JetBrains Mono` installed, which if I understand correctly is the font for the bar configured [here](https://github.com/regolith-linux/regolith-styles/blob/master/dracula/typeface). 

However, if I paste the config file to Gedit, an set it to `JetBrains Mono Medium`, I get the following output:
![image](https://user-images.githubusercontent.com/1499341/210765358-0f846312-f7bf-4a69-9fea-9235269dcd19.png)

Apologies if this is just showing my lack of knowledge of handling fonts. I am happy to modify that configuration with the icons I wish to have in my system, but I wonder whether there could be an issue with the config file?

**Comment by kgilmer** [comment]
Another detail is that between 1.x and 2.x is when the `nerdfonts` change was introduced.  This broke all of the blockets because the unicode character codes representing glyphs changed.  It may be that somehow glyph values are coming from a 1.6 config?  You could check this for the `cpu-usage` blocklet.  Here is the baseline icon config: https://github.com/regolith-linux/regolith-i3xrocks-config/blob/master/scripts/cpu-usage#LL48C42-L48C60

You can see what the glyph value is w `xrescat i3xrocks.label.cpu`.  You may have the older glyphs if you copied or are continuing to use the Dracula look files from 1.6.  You can compare your local copies to what's here: https://github.com/regolith-linux/regolith-look-extra/tree/main/usr/share/regolith-look/dracula

**Comment by diogoalmeida** [comment]
Many thanks for the detailed answer. I will give it a go next week and update the issue once I try it out.

**Comment by diogoalmeida** [comment]
Update: 

Indeed I seem to have been mixing regolith1.6 configs with regolith2. I tried to purge `regolith-i3xrocks-config` and reinstall, which didn't fix the issue, but fully purging regolith, `rm`-ing all of the leftover regolith directories and reinstalling following the instructions in the regolith2 page sorted my issue out and now I have a beautiful set of icons :)

Thanks for bearing with me. I am sure that this can be solved in a more elegant way, but hopefully this thread will be useful to someone else.
