### ISSUE TITLE
Wrong battery instance in battery3

### ISSUE THREAD

**Issue by irenebravo** [regolith-linux/regolith-i3xrocks-config#19]
I recently updated to Ubuntu 19.10 and Regolith 1.3 on my laptop and I noticed that the battery indicator disappeared from the bar.

I checked the i3xrocks config file and for some reason it specified under battery3 instance=BAT0, the command "upower -e | grep -o 'BAT[0-9]' | head -n 1" instead, was showing BAT1.

I replaced BAT0 and BAT1 and everything worked. Probably there is a problem in identifying the battery on installation.

**Comment by baldrailers** [comment]
@irenebravo As far as I know, the instance will take precedence, so if you changed the config `~/.config/regolith/i3xrocks/config` with`instance=BAT1` it will sure work. Some OS will recognize or assign different battery instances, thus the `grep -o 'BAT[0-9]`. I think the safest is just not to declare any instance at all ;)

**Comment by irenebravo** [comment]
I agree, probably it's better to remove the instance from the default configuration :)

**Comment by baldrailers** [comment]
@irenebravo I've already created a PR #20  for this ;)

cc @kgilmer

**Comment by kgilmer** [comment]
Yep, I didn't realize I was hardcoding the battery device.  Thanks for the fix @baldrailers and I'll update the ticket when the fix makes it to the `release` PPA.

**Comment by kgilmer** [comment]
This was addressed in 1.3.1.
