### ISSUE TITLE
Position of tray icons

### ISSUE THREAD

**Issue by MerlinElMago** [regolith-linux/regolith-i3xrocks-config#2]
Hello,
as suggested at [https://regolith-linux.org/howto.html#i3-tray](url) I have activated my tray icons, because I have some programs (as solaar) that needed it. I do have a very minimalistic bar configuration though, just the hour and system load. Is there any way to control the order of the icons? I'd like to leave the hour the farthest right while having the tray icons apear on its left side. 

Is that possible somehow?

Best Regards

**Comment by kgilmer** [comment]
It's possible, but it will require [patching i3bar](https://github.com/Airblader/i3/blob/gaps-next/i3bar/src/xcb.c#L707).  It cannot be done via configuration from my search.  There is [this suggestion](https://www.reddit.com/r/i3wm/comments/50sb64/i3wm_moving_the_tray_icons_in_status_bar/) but after reading about it, it's not clear to me how this would be configured with i3.

**Comment by leosunmo** [comment]
https://wiki.archlinux.org/index.php/Stalonetray
Is a solution mentioned in that thread. It's supposed to work well with a variety of WMs. Could give it a try. 

Do you have an application that adds a tray icon that I could easily test with?

**Comment by kgilmer** [comment]
Closing, as this is really a feature request for i3-gaps.  @MerlinElMago , I suggest you create an issue for i3-gaps for this feature.
