### ISSUE TITLE
Scripts can hang i3xrocks

### ISSUE THREAD

**Issue by Michionlion** [regolith-linux/regolith-i3xrocks-config#21]
I've observed this with both the `wifi2` script and `cpu_usage` script, which exhibit different behavior when clicked. The `wifi2` script will block any updates from happening to the `wifi2` component while the wifi configuration window is open, but other parts of the bar will continue updating. However, something weirder is going on, because just adding a `&` to the executable call changes nothing, and neither does using `i3-msg -q exec`.

`cpu_usage` is a little more complicated, because while the process monitor is open, the entire bar is frozen. I would guess that perl is not doing what would be expected with the `system('/usr/bin/gnome-system-monitor &')` call, which is perhaps related to [this](https://www.perlmonks.org/?node_id=124129) perlmonks question.

**Comment by kgilmer** [comment]
Hi @Michionlion ! Thanks for the detailed bug report :smile: .  I must have better luck with `i3-msg -q exec` than you...did you reload the i3 config after making the change?

**Comment by kgilmer** [comment]
Reopening for verification.

**Comment by Michionlion** [comment]
Yes, reloaded and completely restarted. Maybe something is wrong in my environment then? It's not a completely new install, I was using bare i3 on Ubuntu before.

**Comment by kgilmer** [comment]
@Michionlion are you able to verify if this is fixed for you in Regolith 1.3.1?

**Comment by kgilmer** [comment]
Closing due to no response.

**Comment by Michionlion** [comment]
Sorry about the long wait but yes, it seems this was fixed at some point... most likely 1.3.1 or 1.4. Thanks!
