### ISSUE TITLE
Battery is not showing

### ISSUE THREAD

**Issue by Afsalmc** [regolith-linux/regolith-i3xrocks-config#29]
Battery percentage is not showing in i3bar . tried changing value of instance in i3xrocks config file but no effects .
i got this issue in intel Atom z3735f baytrail with 2gb ram on 64-bit Ubuntu 19.10 with a 32-bit UEFI . 
output of "upower -e" in my system :--
/org/freedesktop/UPower/devices/line_power_axp288_charger
/org/freedesktop/UPower/devices/battery_axp288_fuel_gauge
/org/freedesktop/UPower/devices/DisplayDevice
but as stated above assigning battery_axp288_fuel_gauge or axp288_fuel_gauge to instance variable in the i3xrocks config file didnt solve my issue .

**Comment by kgilmer** [comment]
What is the output of `/usr/share/i3xrocks/battery` print?

**Comment by Afsalmc** [comment]
> What is the output of `/usr/share/i3xrocks/battery` print?

bash: /usr/share/i3xrocks/battery: No such file or directory

**Comment by kgilmer** [comment]
Hmm, how about `apt list --installed | grep regolith` and `apt policy | grep regolith` ?

**Comment by Afsalmc** [comment]
>`apt list --installed | grep regolith` 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

regolith-compositor-compton-glx/eoan,now 1.0.3-1ubuntu1~ppa1 amd64
[installed,automatic]
regolith-desktop/eoan,now 2.47-1ubuntu1~ppa1 amd64 [installed]
regolith-ftue/eoan,now 1.0.2-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-gnome-flashback/eoan,now 2.2.6-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3-gaps-config/eoan,now 2.2.7-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3xrocks-config/eoan,now 2.2.7-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-look-cahuella/eoan,now 2.2.15-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-rofication/eoan,now 1.0.7-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-st/eoan,now 0.8.2-1ubuntu20ppa5 amd64 [installed,automatic]
regolith-styles/eoan,now 2.2.15-1ubuntu1~ppa1 amd64 [installed,automatic]
> 'apt policy | grep regolith'
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

 500 http://ppa.launchpad.net/regolith-linux/r1.3/ubuntu eoan/main
i386 Packages
     release v=19.10,o=LP-PPA-regolith-linux-r1.3,a=eoan,n=eoan,l=Regolith Linux - Release 1.3,c=main,b=i386
 500 http://ppa.launchpad.net/regolith-linux/r1.3/ubuntu eoan/main
amd64 Packages
     release v=19.10,o=LP-PPA-regolith-linux-r1.3,a=eoan,n=eoan,l=Regolith Linux - Release 1.3,c=main,b=amd64

**Comment by Afsalmc** [comment]
> What is the output of `/usr/share/i3xrocks/battery` print?

File battery is non existing in the /usr/share/i3xrocks folder but similiar file battery3 is found . 
> output of  cat /usr/share/i3xrocks/battery3
```
#!/bin/bash
# Battery blocklet for Regolith
# This script was adapted from https://github.com/hastinbe/i3blocks-battery-plus

LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

# Get battery status.
#
# Returns:
#   The battery's status or state.
get_battery_status() {
    echo "$__UPOWER_INFO" | awk -W posix '$1 == "state:" {print $2}'
}

# Get battery percentage.
#
# Returns:
#   The battery's percentage, without the %.
get_battery_percent() {
    echo "$__UPOWER_INFO" | awk -W posix '$1 == "percentage:" { gsub("%","",$2); print $2}'
}

BATT_DEVICE=$(upower -e | grep -o 'BAT[0-9]' | head -n 1)
__UPOWER_INFO=$(upower --show-info "/org/freedesktop/UPower/devices/battery_${BLOCK_INSTANCE:-$BATT_DEVICE}")

BATT_PERCENT=$(get_battery_percent)
CHARGE_STATE=$(get_battery_status)

if [ -z "$BATT_PERCENT" ]; then
  exit 0
elif [ "$BATT_PERCENT" -ge 0 ] && [ "$BATT_PERCENT" -le 20 ]; then
  LABEL_ICON=$(xrescat i3xrocks.label.battery0 E)
  VALUE_COLOR=$(xrescat i3xrocks.critical.color red)
elif [ "$BATT_PERCENT" -ge 20 ] && [ "$BATT_PERCENT" -le 50 ]; then
  LABEL_ICON=$(xrescat i3xrocks.label.battery20 L)
  VALUE_COLOR=$(xrescat i3xrocks.error.color orange)
elif [ "$BATT_PERCENT" -ge 50 ] && [ "$BATT_PERCENT" -le 80 ]; then
  LABEL_ICON=$(xrescat i3xrocks.label.battery50 M)
  VALUE_COLOR=$(xrescat i3xrocks.nominal white)
elif [ "$BATT_PERCENT" -ge 80 ] && [ "$BATT_PERCENT" -le 98 ]; then
  LABEL_ICON=$(xrescat i3xrocks.label.battery80 F)
  VALUE_COLOR=$(xrescat i3xrocks.nominal white)
else 
  LABEL_ICON=$(xrescat i3xrocks.label.battery100 C)
  VALUE_COLOR=$(xrescat i3xrocks.nominal white)
fi

if [ -z "$CHARGE_STATE" ]; then
  exit 0
elif [ "$CHARGE_STATE" == "discharging" ]; then
  CHARGE_ICON=$(xrescat i3xrocks.label.dn D)
elif [ "$CHARGE_STATE" == "charging" ]; then
  CHARGE_ICON=$(xrescat i3xrocks.label.up C)
else
  CHARGE_ICON=$(echo -e '\u2003')
fi

echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $BATT_PERCENT%</span><span color=\"${LABEL_COLOR}\">$CHARGE_ICON</span>"

if [ ! -z "$button" ]; then
    /usr/bin/gnome-control-center power
fi
```

**Comment by kgilmer** [comment]
Ok, you're on the r1.3 PPA.  This version of Regolith had a different name for the battery script: `/usr/share/i3xrocks/battery2`.  Does that run for you?

**Comment by kgilmer** [comment]
Thanks for the detailed debuging info, very helpful.  You're the first person to report an issue like this.  I wonder how common this battery naming convention is.  Can you share the make and model of the computer you're using?

**Comment by Afsalmc** [comment]
> Thanks for the detailed debuging info, very helpful. You're the first person to report an issue like this. I wonder how common this battery naming convention is. Can you share the make and model of the computer you're using?

This is a very cheap notebook based on baytrail intel atoms . These laptops have 32bit Uefi and a 64bit Processor(much weird). I'm using an India exclusive notebook by Iball india , model : Compbook Excelance ver 1.0

Link to project page : https://www.iball.co.in/Product/Excelance/11187

Hope Regolith as a distro and DE reach more and more linux users and thanks for your amazing work of making my daily driver DE .

**Comment by Afsalmc** [comment]
Another thing to be noted that battery percentage was working well with default configurations when now depracated ppa:kgilmer/regolith-stable was in use .

**Comment by kgilmer** [comment]
Looking back over this issue @Afsalmc , it's not clear to me why setting `BLOCK_INSTANCE` to the battery device name doesn't work for you.  This line:
```
__UPOWER_INFO=$(upower --show-info "/org/freedesktop/UPower/devices/battery_${BLOCK_INSTANCE:-$BATT_DEVICE}")
```
As I understand it, the BLOCK_INSTANCE value should be taken, and if it doesn't exist then BATT_DEVICE is the fallback.  If you specify `BLOCK_INSTANCE=axp288_battery_gauge` in the config file, does it work?

**Comment by Afsalmc** [comment]
`__UPOWER_INFO=$(upower --show-info "/org/freedesktop/UPower/devices/battery_${BLOCK_INSTANCE:-$BATT_DEVICE}")`
**The above  command alone doesn't work .**

>BLOCK_INSTANCE=axp288_battery_gauge in the config file, does it work?
Nope . specifying  instance variable in config doesn't work .

**Comment by ajpen** [comment]
@kgilmer Just to add, I installed regolith on a LG Gram 13 running Ubuntu 19.10 and was seeing the same as @Afsalmc mentioned. `upower -e` gives: 

```
/org/freedesktop/UPower/devices/line_power_ADP1
/org/freedesktop/UPower/devices/battery_CMB0
/org/freedesktop/UPower/devices/mouse_hid_34o88o5do57oe5of3_battery
/org/freedesktop/UPower/devices/DisplayDevice
```

**Comment by kgilmer** [comment]
Good to know, thanks @ajpen and @Afsalmc .  I will try and make the battery block work better for various device paths.

**Comment by pedrokost** [comment]
I believe this issue should be resolved by #78

**Comment by kgilmer** [comment]
Closing as fixed by #78

**Comment by bierm4nn** [comment]
Hallo,

I had the same Issue with Ubuntu 20.04, Regolith 1.5 and a Thinkpad T460s.

I first tried the tutorial which suggested to use "ls /sys/class/power_supply/". This listed the batteries as BAT0 and BAT1. However using "upower -e" as suggested by @ajpen showed "battery_BAT0" and "battery_BAT1". Using those in the config file 80_battery worked for me :)

Thanks!

**Comment by jthegedus** [comment]
I had a vanilla Ubuntu 20.04 installation and heard about Regolith. I found myself on this page https://regolith-linux.org/download/ which doesn't communicate the existance of `regolith-desktop-mobile` and so I had the "standard" installation. Installing the mobile version resolved my issue. 

Perhaps the download page can be updated to reflect the option available as the docs do on this page - https://regolith-linux.org/docs/getting-started/install/#option-2-regolith-desktop-via-repository-ppa

**Comment by kgilmer** [comment]
Thanks for the feedback @jthegedus .  Actually the info about the various options was there, but perhaps not the most obvious.  I've updated the text to more clear about the options available.

**Comment by jthegedus** [comment]
Ah I see there's a link to the entire set of packages. My bad, I have become what I hate, a user who did not read the instructions thoroughly :facepalm:

**Comment by kgilmer** [comment]
Haha, no I agree it wasn't very obvious.  I skim as well.  It's kind of required given the amount we read.  In any case, I would find it helpful if you can take a peek at the revised version and LMK if you think it needs anything else.  Thanks!

https://regolith-linux.org/download/

**Comment by jthegedus** [comment]
Looks great! Hopefully this is the first and last time this happens :sweat_smile:

**Comment by rtud** [comment]
> Hallo,
> 
> I had the same Issue with Ubuntu 20.04, Regolith 1.5 and a Thinkpad T460s.
> 
> I first tried the tutorial(https://regolith-linux.org/docs/howto/multiple-batteries/) which suggested to use "ls /sys/class/power_supply/". This listed the batteries as BAT0 and BAT1. However using "upower -e" as suggested by @ajpen showed "battery_BAT0" and "battery_BAT1". Using those in the config file 80_battery worked for me :)
> 
> Thanks!

Worked like a charm for me on a Thinkpad x260 running Ubuntu 20.04. Thanks for the tip!

**Comment by prismspecs** [comment]
> Haha, no I agree it wasn't very obvious. I skim as well. It's kind of required given the amount we read. In any case, I would find it helpful if you can take a peek at the revised version and LMK if you think it needs anything else. Thanks!
> 
> https://regolith-linux.org/download/

I know what I'm looking for and I still don't see the mobile part, where is t?

**Comment by kgilmer** [comment]
https://regolith-linux.org/docs/getting-started/install/#desktop-packages

**Comment by jthegedus** [comment]
@prismspecs The text on that page:

>Regolith can be installed in an existing Ubuntu 18.04, 20.04, or 20.10 system by adding a Regolith PPA and installing one of the [regolith-desktop packages](https://regolith-linux.org/docs/getting-started/install/#desktop-packages). Advantages to Regolith via PPA:

Links to the download of the other packages

**Comment by BlameTroi** [comment]
Just a quick note in case this happens to anyone else--lubuntun 22.04 after loading stable regolith ppa I also have problems with multiple batteries. the upower -e command gave me the correct names. I note that the names reported in /sys/class/powersupply are symlinks. 

[reg-policy.txt](https://github.com/regolith-linux/regolith-i3xrocks-config/files/10181349/reg-policy.txt)

[reg-installed.txt](https://github.com/regolith-linux/regolith-i3xrocks-config/files/10181350/reg-installed.txt)
