### ISSUE TITLE
Labels of scripts are hardcoded

### ISSUE THREAD

**Issue by MerlinElMago** [regolith-linux/regolith-i3xrocks-config#3]
With the latest update, the icons of the various blocks are hardcoded inside the scripts. This way, adding a custom label to a block, duplicates the original label and the custom label.
![regolith](https://user-images.githubusercontent.com/3123151/63581274-98bc0e80-c58e-11e9-83a9-9e458a40238a.png)

Best regards

**Comment by kgilmer** [comment]
Hi @MerlinElMago !  You are adding the custom label in the i3xrocks config file?

**Comment by MerlinElMago** [comment]
Yes, that was a test with my own icons which got interpreted as labes instead of icons.

**Comment by leosunmo** [comment]
Yeah this is a known issue after adding the Pango formatting in to blocklets. I'll take a look at this soon.

**Comment by leosunmo** [comment]
I haven't forgotten about this! I'm still exploring some options around blocklets and Xresources styling. It's a bigger issue that we should think properly about how to implement.

**Comment by MerlinElMago** [comment]
Can I help somehow?

**Comment by leosunmo** [comment]
Hey @MerlinElMago ! I'm still trying to figure out what the best approach is here. We've been discussing it over in the Slack channel. We could rewrite all of these scripts and call out to Xresources to get both label font label colour, value font (not necessarily the same as label font) value colour as well as short text. 

Another thought I had was to have some kind of middleware that deals with the styling. Something like barista.run is tempting. I started on a i3blocks config interpreter for barista and I'll see how it goes. If you're interested in helping let me know! Join Slack if you're in to that kinda thing.

**Comment by kgilmer** [comment]
While we wait for @leosunmo 's new bar, I've updated the Xresrouces and the default i3xrocks scripts to retrieve labels from Xresources.

Definition: https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/i3xrocks

Example: https://github.com/regolith-linux/regolith-styles-typeface-materialdesign

Work remains on scripts that are not on by default.

**Comment by MerlinElMago** [comment]
Sorry guys for not checking my messages in 12 days.

Yeah, I will try the Slack thing as soon as I have a little more time next week and hopefully help to contribute more.

Regards

**Comment by kgilmer** [comment]
Given the state of the icons in Xresources, I think this issue can be closed but re-open if I've missed something.
