### ISSUE TITLE
focused-window-name crash

### ISSUE THREAD

**Issue by cjohnston1158** [regolith-linux/regolith-i3xrocks-config#31]
Apr 09 09:50:37 kachemak i3-gnome-flashback.desktop[37021]: Traceback (most recent call last):
 Apr 09 09:50:37 kachemak i3-gnome-flashback.desktop[37021]:   File "/usr/share/i3xrocks/focused-window-name", line 30, in <module>
 Apr 09 09:50:37 kachemak i3-gnome-flashback.desktop[37021]:     from i3ipc import Connection, Event
 Apr 09 09:50:37 kachemak i3-gnome-flashback.desktop[37021]: ModuleNotFoundError: No module named 'i3ipc'
 Apr 09 09:50:37 kachemak i3-gnome-flashback.desktop[35275]: <3>[focused-window-name] Command '/usr/share/i3xrocks/$BLOCK_NAME' exited unexpectedly with code 1
[_usr_share_i3xrocks_focused-window-name.tar.gz](https://github.com/regolith-linux/regolith-i3xrocks-config/files/4457844/_usr_share_i3xrocks_focused-window-name.tar.gz)

**Comment by kgilmer** [comment]
Hmm, perhaps the `i3ipc-python` package is not installed?  Can you check?

**Comment by cjohnston1158** [comment]
cjohnston@kachemak:~$ dpkg -l | grep i3ipc
ii  i3ipc-python                                     2.1.1-1ubuntu1~ppa4

**Comment by nachovizzo** [comment]
I've fixed this installing i3ipc-python using pip and at my userspace `python3 -m pip install --user  --upgrade i3ipc`

The pkg provided by Ubuntu didn't work for me
```sh
i3ipc-python/bionic,now 2.1.1-1ubuntu1~ppa4 amd64 [installed]
  An improved Python library to control i3wm and sway.
```

**Comment by gdeflaux** [comment]
Confirming that the package wasn't install for me neither. I ran `pip3 install  i3ipc` and it worked.

**Comment by kgilmer** [comment]
Thanks for the verification @gdeflaux . :smile: .  Yes, I believe that I packaged i3ipc-python incorrectly and that is the root-cause of this issue.  I have learned a few things from @farsil about python packaging so think it's an easy fix, just haven't had time yet to dig into it.

**Comment by kgilmer** [comment]
Verified speed-ricer hosted update to i3ipc-python fixes package issue.  Copying package to `unstable`.

**Comment by moritzheiber** [comment]
@kgilmer So this should be fixed for 1.4.2, right? Any way @jensens can verify?

**Comment by kgilmer** [comment]
Yes it should.  @jensens can download and install the deb from the [unstable PPA](https://launchpad.net/~regolith-linux/+archive/ubuntu/unstable) or add the unstable PPA to apt and upgrade the package.

**Comment by moritzheiber** [comment]
I think you meant to summon @cjohnston1158 .. he's the author :wink:

**Comment by cjohnston1158** [comment]
Looks like it was only copied over for bionic, I'm running Focal.

**Comment by kgilmer** [comment]
Please try again @cjohnston1158 .  Now copied to eoan and focal.

**Comment by cjohnston1158** [comment]
I'm still seeing it:

cjohnston at kachemak in ~$ apt-cache policy i3ipc-python i3xrocks-focused-window-name 
i3ipc-python:
  Installed: 2.1.1-1ubuntu1~ppa6
  Candidate: 2.1.1-1ubuntu1~ppa6
  Version table:
 *** 2.1.1-1ubuntu1~ppa6 500
        500 http://ppa.launchpad.net/regolith-linux/unstable/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     2.1.1-1ubuntu1~ppa4 500
        500 http://ppa.launchpad.net/regolith-linux/release/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/regolith-linux/stable/ubuntu focal/main amd64 Packages
i3xrocks-focused-window-name:
  Installed: 3.0.25-2
  Candidate: 3.0.25-2
  Version table:
 *** 3.0.25-2 500
        500 http://ppa.launchpad.net/regolith-linux/unstable/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     3.0.21-1 500
        500 http://ppa.launchpad.net/regolith-linux/release/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/regolith-linux/stable/ubuntu focal/main amd64 Packages
cjohnston at kachemak in ~$ tail -f /var/log/syslog
May 25 10:35:49 kachemak i3-gnome-flashback.desktop[23484]: Traceback (most recent call last):
May 25 10:35:49 kachemak i3-gnome-flashback.desktop[23484]:   File "/usr/share/i3xrocks/focused-window-name", line 30, in <module>
May 25 10:35:49 kachemak i3-gnome-flashback.desktop[23484]:     from i3ipc import Connection, Event
May 25 10:35:49 kachemak i3-gnome-flashback.desktop[23484]: ModuleNotFoundError: No module named 'i3ipc'
May 25 10:35:49 kachemak i3-gnome-flashback.desktop[12565]: <3>[focused-window-name] Command '/usr/share/i3xrocks/$BLOCK_NAME' exited unexpectedly with code 1

**Comment by cjohnston1158** [comment]
```
$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import i3ipc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'i3ipc'
```

```
$ /usr/share/i3xrocks/focused-window-name 
Traceback (most recent call last):
  File "/usr/share/i3xrocks/focused-window-name", line 30, in <module>
    from i3ipc import Connection, Event
ModuleNotFoundError: No module named 'i3ipc'
```

**Comment by moritzheiber** [comment]
Found the issue: `i3ipc-python` is only shipping Python modules for Python 3.*7*, while Focal Fossa is shipping Python 3.*8*.

**Comment by cjohnston1158** [comment]
It looks like the package in unstable now has a dep on python3-i3ipc however that hasn't been copied to unstable.

**Comment by kgilmer** [comment]
Hi Chris, the package is now hosted in `unstable` for focal, eoan, and bionic.

**Comment by cjohnston1158** [comment]
Perfect! Looks great, thanks @kgilmer

**Comment by mrzor** [comment]
I worked around this (still using stable) by adding a couple of symlinks:

`sudo ln -s /usr/lib/python3.7/dist-packages/i3ipc /usr/lib/python3/dist-packages/i3ipc`
`sudo ln -s /usr/lib/python3.7/dist-packages/i3ipc-2.1.1.egg-info /usr/lib/python3/dist-packages/i3ipc-2.1.1.egg-info`

FWIW, i3ipc was the only package I had in `/usr/lib/python3.7` - most of my system python3 packages seem to be in `/usr/lib/python3`

**Comment by kgilmer** [comment]
Thanks for the details @mrzor , to confirm, you're not using the version of i3ipc-python in unstable (i3ipc-python - 2.1.1-1ubuntu1~ppa6), correct?

**Comment by mrzor** [comment]
Here is the output of `dpkg -l i3ipc\*`:
`ii  i3ipc-python   2.1.1-1ubuntu1~ppa4 amd64        An improved Python library to control i3wm and sway.`

I can confirm I'm not using i3ipc-python from unstable :)

**Comment by moritzheiber** [comment]
This should be fixed with the latest release.
