### ISSUE TITLE
keyboard layout issues

### ISSUE THREAD

**Issue by buck10** [regolith-linux/regolith-i3xrocks-config#52]
Hi, I noticed that the keyboard layout does not display properly in the bar if you only have one language setup on your computer. Looks like it is related to an issue with gnome where mru-sources is not initialized on new installs and is only used when multiple languages are installed on the system. I have a fix for this and can issue a pull request if you would like me to do so.

**Comment by moritzheiber** [comment]
@buck10 Sure, happy to see a PR for this

**Comment by buck10** [comment]
OK, I'll get one together. noticed a problem with my solution. hopefully will sort it out soon.

**Comment by buck10** [comment]
Worked out the issues I was seeing and submitted the PR.  I only have english keyboards, but I added a few other languages to see if it switched properly and seems like it is working OK. Let me know if you see any problems.
