### ISSUE TITLE
i3xrocks net-traffic appears and dissaperas on Ubuntu 20.04

### ISSUE THREAD

**Issue by nachovizzo** [regolith-linux/regolith-i3xrocks-config#73]
I just upgraded to Ubuntu 20.04 and this is happening: [video](https://streamable.com/a3pq1y)

The only related issue I've found is on [reddit](https://www.reddit.com/r/i3wm/comments/fwj7r9/net_traffic_block_keeps_appearing_and_disappearing/)

Any idea on how to debug/solve this issue?

**Comment by kgilmer** [comment]
I like the music!

As mentioned in the reddit post, run the net-traffic script from a terminal when it's not visible in the bar.  Generally speaking, what you see in the bar is simply output from the shell scripts in `/usr/share/i3xrocks`

You should either see the correct output, something like: 

```bash
$ /usr/share/i3xrocks/net-traffic 
<span color="#E6E1CF"></span><span font_desc="Source Code Pro Medium 13" color="#E6E1CF">  3.1KB</span><span color="#E6E1CF"></span><span font_desc="Source Code Pro Medium 13" color="#E6E1CF">  2.9KB</span><span color="#E6E1CF"></span>
```

Or something else that may just be error stuff.  This is what we need to determine why you're seeing this problem.

**Comment by nachovizzo** [comment]
Thanks! the music is from Sig Ragga: https://open.spotify.com/artist/7hBKLnKOnLXNBwJ1l6p24J?si=-0iWGoheRaWIdtxfSQQ88Q.

I ran the `net-traffic` from the shell and when there is nothing in the bar, then, there is also nothing in the shell...

```sh
ivizzo (master) /usr/share/i3xrocks/net-traffic 
<span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf">  6,0KB</span><span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf">  5,0KB</span><span color="#e6e1cf"></span>
ivizzo (master) /usr/share/i3xrocks/net-traffic
ivizzo (master) /usr/share/i3xrocks/net-traffic
ivizzo (master) /usr/share/i3xrocks/net-traffic
ivizzo (master) /usr/share/i3xrocks/net-traffic
ivizzo (master) /usr/share/i3xrocks/net-traffic
<span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf"> 70,0 B</span><span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf"> 70,0 B</span><span color="#e6e1cf"></span>
ivizzo (master) /usr/share/i3xrocks/net-traffic
<span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf">  1,0KB</span><span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf">  1,0KB</span><span color="#e6e1cf"></span>
ivizzo (master) /usr/share/i3xrocks/net-traffic
ivizzo (master) /usr/share/i3xrocks/net-traffic
<span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf"> 64,0 B</span><span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf"> 64,0 B</span><span color="#e6e1cf"></span>
```

**Comment by ivandome** [comment]
I ended up here looking for a solution to the same problem in Ubuntu 20.04, reading your comments and playing with the code I found these lines in the script that seem to be the problem:
```
for s in $RN $TN $AN; do
   [[ "$s" = "$(printf "%s\n-0.0001\n" "$s" | sort -g | head -1)" ]] && exit
done
```
They seem like some kind of filter that causes premature exit of the script, I don't have much experience in bash, just comment the block and everything seems to work correctly

**Comment by kgilmer** [comment]
Hi @ivandome , thanks for the tip, very helpful.  I have not been able to reproduce this issue so it's difficult to test.  Yes, the line looks to be formatting the values.  @moritzheiber git says you were the last to touch this line...any thoughts here as to what could cause the script to return no data intermittently?

**Comment by pedrokost** [comment]
@kgilmer The issue can be reproduced when any of RN, TN or AN is 0. 

I've manually modified the script (/usr/share/i3xrocks/net-traffic), to print the variable RN, TN and AN, as shown in the screenshot below. Lines 174-182 have been added for troubleshooting:

![image](https://user-images.githubusercontent.com/725286/94795573-d029fb00-03dd-11eb-8c3a-77acb1ad4a49.png)

The following screenshot shows that when any of the values are 0, the script exits early and does not print the stats.

![image](https://user-images.githubusercontent.com/725286/94795584-d3bd8200-03dd-11eb-8d65-ec4e034e2033.png)


Hope this helps.

**Comment by robin-thoni** [comment]
@kgilmer My understanding is that those lines are supposed to protect against negative/weird values: if the command output is the same as the input, it's a non acceptable value.
Acceptable values:
```
$ printf "42\n-0.0001\n" | sort -g | head -1
-0.0001
$ printf "42.0\n-0.0001\n" | sort -g | head -1
-0.0001
```

Bad values:
```
$ printf "test\n-0.0001\n" | sort -g | head -1
test
$ printf " -1\n-0.0001\n" | sort -g | head -1
 -1
```

Unfortunately, `0` also triggers it:
```
$ printf "0\n-0.0001\n" | sort -g | head -1
0
```

I commented that code out, and didn't get any unexpected behavior (for now). We could:
- fix the test
- remove it
- set the corresponding variable to `0` instead of exiting (in that case, `0` would be corrected to `0`, which is the expected output)

**Comment by kgilmer** [comment]
Hi @robin-thoni , thank you for the clear breakdown of the issue!  Would you be interested in creating a PR that implements your third option?

> set the corresponding variable to 0 instead of exiting (in that case, 0 would be corrected to 0, which is the expected output

**Comment by kgilmer** [comment]
@robin-thoni , @pedrokost has provided a PR that addresses the issue.  Assuming I don't find any problems in testing I will merge it so no action is required here.  Thanks again for your help!  :smile:

**Comment by robin-thoni** [comment]
Was busy this weekend, didn't had time to look at it... Good to see it has been fixed :)

**Comment by kgilmer** [comment]
Closing this as fixed by @pedrokost PR.
