### ISSUE TITLE
Temp Configuration

### ISSUE THREAD

**Issue by nitin88** [regolith-linux/regolith-i3xrocks-config#74]
Hi,

I couldn't find how to customize the configuration of Temperature.
Which sensor value is it picking by default? Can we customize to point to specific sensor?

From my `sensors`, i believe by default it's picking up my wifi temp sensor (which is pointless).

**Comment by kgilmer** [comment]
Good call @nitin88 .  We will fix this in Regolith 1.5 by allowing you to specify a specific sensor via Xres overrides.

**Comment by kgilmer** [comment]
The key to specify the key of the temp sensor you wish to view will be `i3xrocks.temp.key`.

**Comment by kgilmer** [comment]
This has been addressed in 1.5 by providing an average of temperatures rather than specifying a specific sensor in the configuration.
