### ISSUE TITLE
Pango markup does not work as expected in self-written blocklets

### ISSUE THREAD

**Issue by Interesting-name** [regolith-linux/regolith-i3xrocks-config#8]
Hello again,

Trying out the inactive mediaplayer blocklet that ships with regolith (located in `/usr/share/i3xrocks/mediaplayer`), I noticed that the ouput is not formatted. I thus wrote a very simple script that imitates the formatting from the other, pre-formatted blocklets:

```sh
#!/bin/bash                                                                     
                                                                                
STATUS=$(playerctl status)                                                      
                                                                                
if [ $STATUS == 'Playing' ]; then
  playerctl metadata -f "<span_color=\"#81A1C1\"></span><span font_desc=\"Source Code Pro Medium 13\" color=\"#D8DEE9\"> {{ artist }} - {{ title }}</span>"
elif [ $STATUS == 'Paused' ]; then
  playerctl metadata -f "<span_color=\"#81A1C1\"></span><span font_desc=\"Source Code Pro Medium 13\" color=\"#D8DEE9\"> {{ artist }} - {{ title }}</span>"
elif [ $STATUS == 'Stopped' ]; then
  playerctl metadata -f "<span_color=\"#81A1C1\"></span><span font_desc=\"Source Code Pro Medium 13\" color=\"#D8DEE9\"> {{ artist }} - {{ title }}</span>"
else
  echo ""
fi
echo ""
exit 0
```

I hardcoded the icons for the beginning, this is of course easily changed. My problem now is that this is not rendered at all.

I tested a few iterations and the one that works for me has no formatting, like so:

```sh
#!/bin/bash                                                                     
                                                                                
STATUS=$(playerctl status)                                                      
                                                                                
if [ $STATUS == 'Playing' ]; then
  playerctl metadata -f "  {{ artist }} - {{ title }}"
elif [ $STATUS == 'Paused' ]; then
  playerctl metadata -f "  {{ artist }} - {{ title }}"
elif [ $STATUS == 'Stopped' ]; then
  playerctl metadata -f "  {{ artist }} - {{ title }}"
else
  echo ""
fi
echo ""
exit 0
```

I also looked at the error messages given by invoking i3xrocks with the `-vvv` option, (changing the line `status_command i3xrocks -c $i3xrocks_config` from the i3 config to `status_command 2>/tmp/i3xrocks.err i3xrocks -vvv -c $i3xrocks_config | tee /tmp/i3xrocks.out`), but there didn't seem to be anything out of the ordinary.

Unfortunately, I'm at my wit's end here. I can't seem to find any difference in the formatting between the blocklets that work (i.e. the default ones) and my improvised blocklet.
What am I missing here?

**Comment by Interesting-name** [comment]
After a bit of testing, I found out that playerctl doesn't handle the format string very well.
The following works perfectly:
```bash
#!/bin/bash

STATUS=$(playerctl status)

# use given value or fall back to parameters from xresources
PLAYING_ICON=${icon:-$(xrescat i3xrocks.label.mediaplaying)}
PAUSED_ICON=${icon:-$(xrescat i3xrocks.label.mediapaused)}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

case $STATUS in
  'Playing') ICON=${PLAYING_ICON} ;;
  'Paused') ICON=${PAUSED_ICON} ;;
  'Stopped') ICON=${PAUSED_ICON} ;;
  *) echo "" ; echo "" ; exit 0 ;;
esac

ARTIST="$(playerctl metadata artist)"
TITLE="$(playerctl metadata title)"


echo "<span color=\"${LABEL_COLOR}\">${ICON}</span>\
<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> \
${ARTIST} - ${TITLE}</span>"

echo $ICON

exit 0

```

**Comment by kgilmer** [comment]
Glad you figured it out @Interesting-name .  Would you be interested in submitting this script as a PR to the i3xrocks repo?

https://github.com/regolith-linux/regolith-i3xrocks-config/tree/master/scripts

**Comment by Interesting-name** [comment]
Hey @kgilmer, I'd definitely do that! I suppose it would be more functional and more efficient to adapt the perl script that's already there, although it shouldn't hurt to have both options! Since I've never done anything like this before, can you point me to a beginner's tutorial on how to submit?

Also, there would have to be some additional glyph definitions. I used these: [playing](https://fontawesome.com/icons/play?style=solid), [paused/stopped](https://fontawesome.com/icons/pause?style=solid)

**Comment by kgilmer** [comment]
Sure, so you would need to submit two [github pull requests](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests).  First, for your script, you would add the file in the repo regolith-i3xrocks-config, in here: https://github.com/regolith-linux/regolith-i3xrocks-config/tree/master/scripts
Second, for the Xresources additions, you would create a PR in regolith-styles.  The PR would define the icon values in these files:

https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/typeface-sourcecodepro
https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/typeface-ubuntu

and then bind them to the i3xrocks Xresource keys in this file:

https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/i3xrocks

Once you've created the PRs, we review them, and once pushed I will do a Debian build of the changes so that everyone can get the new script in their system if they want this blocklet.
