### ISSUE TITLE
Custom configuration not working?

### ISSUE THREAD

**Issue by dobrevdelyo** [regolith-linux/regolith-i3xrocks-config#83]
Hi, I'm getting used to Regolith and like it so far, but I'm having problems customizing

I wanted to change my i3xrocks status indicators so i followed the tutorial, staged an i3 config file, changed the i3xrocks configuration files location in the i3 config, and copied the status indicators from source to `~/.config/regolith/i3xrocks/conf.d` along with their respective scripts in `/usr/share/i3xrocks`.
When i save the i3/config file, reboot, log out, restart i3 or refresh config, with this setup, my bar shows:
`Error: status command not found or is missing a library dependency (exit 127)`

For some reason the i3bar only loads the status indicators when i reset them to be loaded from the default `/etc` directory despite having copied the exact same files and supposedly rerouted `i3/config` to load `~/.config/regolith/i3xrocks/conf.d` (after trying the single-file variant).
As soon as i Override the default i3xrocks configuration file the bar either shows the error message or is blank.

**Comment by moritzheiber** [comment]
Could you please join us on Slack? The bug tracker is not meant for general help or solving configuration issues. Thanks for understanding! :slightly_smiling_face:
