### ISSUE TITLE
i3xrocks-net-traffic shows 0kb/0kb when there is traffic

### ISSUE THREAD

**Issue by morten-b** [regolith-linux/regolith-i3xrocks-config#91]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ ] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

In some situations i3xrocks-net-traffic shows 0kb/0kb when there is traffic. It is observed when on a Zoom session, and possibly also when streaming video and when sending data via UDP.

**To Reproduce**
Run a Zoom session or run `iperf3 -c ping.online.net -p 5203 -u` which will send via UDP. If removing `-u` it send via TCP, which does not seem to be affected.

**Expected behavior**
i3xrocks-net-traffic shows amount of traffic transmitted.

**Screenshots**
https://ibb.co/YDqjG2V

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 1.5
 - PPA url: ppa:regolith-linux/stable
 - Host OS (for PPA): e.g. Ubuntu 20.10

**Comment by moritzheiber** [comment]
@morten-b Can you do me a favor and try out the "new" `net-traffic` script from #92? You can download it here: https://raw.githubusercontent.com/regolith-linux/regolith-i3xrocks-config/e59b20c7c923f7c7484ae96e38323140341d6d7c/scripts/net-traffic

**Comment by moritzheiber** [comment]
If ti doesn't work for you we'll have to come up with better tests. Otherwise it's a huge improvement over the last script.

**Comment by morten-b** [comment]
I've replaced it with `/usr/share/i3xrocks/net-traffic` and tried to rerun the `iperf3 -c ping.online.net -p 5204 -u` command. iperf returns:
```
Connecting to host ping.online.net, port 5204
[  5] local 192.168.1.123 port 50470 connected to 62.210.18.40 port 5204
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-1.00   sec   129 KBytes  1.05 Mbits/sec  91  
[  5]   1.00-2.00   sec   127 KBytes  1.04 Mbits/sec  90  
[  5]   2.00-3.00   sec   129 KBytes  1.05 Mbits/sec  91  
[  5]   3.00-4.00   sec   129 KBytes  1.05 Mbits/sec  91  
[  5]   4.00-5.00   sec   127 KBytes  1.04 Mbits/sec  90  
[  5]   5.00-6.00   sec   129 KBytes  1.05 Mbits/sec  91  
[  5]   6.00-7.00   sec   127 KBytes  1.04 Mbits/sec  90  
[  5]   7.00-8.00   sec   129 KBytes  1.05 Mbits/sec  91  
[  5]   8.00-9.00   sec   127 KBytes  1.04 Mbits/sec  90  
[  5]   9.00-10.00  sec   129 KBytes  1.05 Mbits/sec  91  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.000 ms  0/906 (0%)  sender
[  5]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.322 ms  0/906 (0%)  receiver
```
while the tray show upload traffic around 150K, while for TCP its in the area of 10M, so i guess it didn't work as hoped for.
