### ISSUE TITLE
volume applet update

### ISSUE THREAD

**Issue by geolaw** [regolith-linux/regolith-i3xrocks-config#97]
I don't see a "feature request" option.

on ubuntu 20.10 
I've replaced the installed i3xrocks-volume version 
ii  i3xrocks-volume 3.2.6-1ubuntu2 amd64        Indicator to show volume.

with the most recent volume script from github, 

I noticed the left click action was empty - my personal preference would be a quick way to get to the sound settings on left click

ACTION_1=$(xrescat i3xrocks.action.volume.left "gnome-control-center sound --class=floating_window")

**Comment by kgilmer** [comment]
Hi @geolaw , yeah that's not a bad idea.  Let me think about the inclusion of this as default.  For now, you can just add an Xres override to get this behavior w/out modifying any scripts.

`~/.config/regolith/Xresources`:
```
i3xrocks.action.volume.left: gnome-control-center sound --class=floating_window
```

**Comment by geolaw** [comment]
Yes - I figured that out after I posted this tweaking the "time" script to open gnome-calendar upon click with 
i3xrocks.action.time:gnome-calendar --class=floating_window
closing -
